/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


/**
 *
 * @author Alunos
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public TelaMenu() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        agenMenuTitle = new javax.swing.JMenu();
        agenCriarTitle = new javax.swing.JMenuItem();
        agenEditarTitle = new javax.swing.JMenuItem();
        agenExcluirTitle = new javax.swing.JMenuItem();
        agenConsultarTitle = new javax.swing.JMenuItem();
        clienteMenuTitle = new javax.swing.JMenu();
        clienteCriarTitle = new javax.swing.JMenuItem();
        clienteEditarTitle = new javax.swing.JMenuItem();
        clienteExcluirTitle = new javax.swing.JMenuItem();
        clienteConsultarTitle = new javax.swing.JMenuItem();
        contaMenuTitle = new javax.swing.JMenu();
        contaCriarTitle = new javax.swing.JMenuItem();
        contaEditarTitle = new javax.swing.JMenuItem();
        contaExcluirTitle = new javax.swing.JMenuItem();
        contaConsultarTitle = new javax.swing.JMenuItem();
        extratoMenuTitle = new javax.swing.JMenu();
        extratoCriarTitle = new javax.swing.JMenuItem();
        extratoEditarTitle = new javax.swing.JMenuItem();
        extratoExcluirTitle = new javax.swing.JMenuItem();
        extratoConsultarTitle = new javax.swing.JMenuItem();
        histMenuTitle = new javax.swing.JMenu();
        histCriarTitle = new javax.swing.JMenuItem();
        histEditarTitle = new javax.swing.JMenuItem();
        histExcluirTitle = new javax.swing.JMenuItem();
        histConsultarTitle = new javax.swing.JMenuItem();
        usuarioMenuTitle = new javax.swing.JMenu();
        usuarioCriarTitle = new javax.swing.JMenuItem();
        usuarioEditarTitle = new javax.swing.JMenuItem();
        usuarioExcluirTitle = new javax.swing.JMenuItem();
        usuarioConsultarTitle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agenMenuTitle.setText("Agencia");

        agenCriarTitle.setText("Criar");
        agenCriarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenCriarTitleActionPerformed(evt);
            }
        });
        agenMenuTitle.add(agenCriarTitle);

        agenEditarTitle.setText("Editar");
        agenEditarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenEditarTitleActionPerformed(evt);
            }
        });
        agenMenuTitle.add(agenEditarTitle);

        agenExcluirTitle.setText("Excluir");
        agenExcluirTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenExcluirTitleActionPerformed(evt);
            }
        });
        agenMenuTitle.add(agenExcluirTitle);

        agenConsultarTitle.setText("Consultar");
        agenConsultarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenConsultarTitleActionPerformed(evt);
            }
        });
        agenMenuTitle.add(agenConsultarTitle);

        jMenuBar1.add(agenMenuTitle);

        clienteMenuTitle.setText("Cliente");
        clienteMenuTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuTitleActionPerformed(evt);
            }
        });

        clienteCriarTitle.setText("Criar");
        clienteCriarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCriarTitleActionPerformed(evt);
            }
        });
        clienteMenuTitle.add(clienteCriarTitle);

        clienteEditarTitle.setText("Editar");
        clienteEditarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEditarTitleActionPerformed(evt);
            }
        });
        clienteMenuTitle.add(clienteEditarTitle);

        clienteExcluirTitle.setText("Excluir");
        clienteExcluirTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteExcluirTitleActionPerformed(evt);
            }
        });
        clienteMenuTitle.add(clienteExcluirTitle);

        clienteConsultarTitle.setText("Consultar");
        clienteConsultarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteConsultarTitleActionPerformed(evt);
            }
        });
        clienteMenuTitle.add(clienteConsultarTitle);

        jMenuBar1.add(clienteMenuTitle);

        contaMenuTitle.setText("Conta");

        contaCriarTitle.setText("Criar");
        contaCriarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaCriarTitleActionPerformed(evt);
            }
        });
        contaMenuTitle.add(contaCriarTitle);

        contaEditarTitle.setText("Editar");
        contaEditarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaEditarTitleActionPerformed(evt);
            }
        });
        contaMenuTitle.add(contaEditarTitle);

        contaExcluirTitle.setText("Excluir");
        contaExcluirTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaExcluirTitleActionPerformed(evt);
            }
        });
        contaMenuTitle.add(contaExcluirTitle);

        contaConsultarTitle.setText("Consultar");
        contaConsultarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaConsultarTitleActionPerformed(evt);
            }
        });
        contaMenuTitle.add(contaConsultarTitle);

        jMenuBar1.add(contaMenuTitle);

        extratoMenuTitle.setText("Extrato");

        extratoCriarTitle.setText("Criar");
        extratoCriarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoCriarTitleActionPerformed(evt);
            }
        });
        extratoMenuTitle.add(extratoCriarTitle);

        extratoEditarTitle.setText("Editar");
        extratoEditarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoEditarTitleActionPerformed(evt);
            }
        });
        extratoMenuTitle.add(extratoEditarTitle);

        extratoExcluirTitle.setText("Excluir");
        extratoExcluirTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoExcluirTitleActionPerformed(evt);
            }
        });
        extratoMenuTitle.add(extratoExcluirTitle);

        extratoConsultarTitle.setText("Consultar");
        extratoConsultarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoConsultarTitleActionPerformed(evt);
            }
        });
        extratoMenuTitle.add(extratoConsultarTitle);

        jMenuBar1.add(extratoMenuTitle);

        histMenuTitle.setText("Histórico");

        histCriarTitle.setText("Criar");
        histCriarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histCriarTitleActionPerformed(evt);
            }
        });
        histMenuTitle.add(histCriarTitle);

        histEditarTitle.setText("Editar");
        histEditarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histEditarTitleActionPerformed(evt);
            }
        });
        histMenuTitle.add(histEditarTitle);

        histExcluirTitle.setText("Excluir");
        histExcluirTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histExcluirTitleActionPerformed(evt);
            }
        });
        histMenuTitle.add(histExcluirTitle);

        histConsultarTitle.setText("Consultar");
        histConsultarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histConsultarTitleActionPerformed(evt);
            }
        });
        histMenuTitle.add(histConsultarTitle);

        jMenuBar1.add(histMenuTitle);

        usuarioMenuTitle.setText("Usuário");
        usuarioMenuTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuTitleActionPerformed(evt);
            }
        });

        usuarioCriarTitle.setText("Criar");
        usuarioCriarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCriarTitleActionPerformed(evt);
            }
        });
        usuarioMenuTitle.add(usuarioCriarTitle);

        usuarioEditarTitle.setText("Editar");
        usuarioEditarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEditarTitleActionPerformed(evt);
            }
        });
        usuarioMenuTitle.add(usuarioEditarTitle);

        usuarioExcluirTitle.setText("Excluir");
        usuarioExcluirTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioExcluirTitleActionPerformed(evt);
            }
        });
        usuarioMenuTitle.add(usuarioExcluirTitle);

        usuarioConsultarTitle.setText("Consultar");
        usuarioConsultarTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioConsultarTitleActionPerformed(evt);
            }
        });
        usuarioMenuTitle.add(usuarioConsultarTitle);

        jMenuBar1.add(usuarioMenuTitle);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteMenuTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuTitleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clienteMenuTitleActionPerformed

    private void usuarioMenuTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioMenuTitleActionPerformed

    private void clienteCriarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCriarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        TelaClientes acesso_cliente = new TelaClientes(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_clienteCriarTitleActionPerformed

    private void usuarioCriarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCriarTitleActionPerformed
        String operacao = "Incluir";
        TelaUsuarios acesso_usuario = new TelaUsuarios(operacao);
        acesso_usuario.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_usuarioCriarTitleActionPerformed

    private void contaCriarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaCriarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        TelaContas acesso_conta = new TelaContas(operacao);
        acesso_conta.setVisible(true);
    }//GEN-LAST:event_contaCriarTitleActionPerformed

    private void agenCriarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenCriarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        TelaAgencias acesso_agencia = new TelaAgencias(operacao);
        acesso_agencia.setVisible(true);
    }//GEN-LAST:event_agenCriarTitleActionPerformed

    private void extratoCriarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratoCriarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        TelaExtratos acesso_extrato = new TelaExtratos(operacao);
        acesso_extrato.setVisible(true);
    }//GEN-LAST:event_extratoCriarTitleActionPerformed

    private void histCriarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histCriarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        TelaHistoricos acesso_historico = new TelaHistoricos(operacao);
        acesso_historico.setVisible(true);
    }//GEN-LAST:event_histCriarTitleActionPerformed

    private void clienteEditarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEditarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        TelaClientes acesso_cliente = new TelaClientes(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_clienteEditarTitleActionPerformed

    private void clienteExcluirTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteExcluirTitleActionPerformed
        String operacao = "Excluir";
        TelaClientes acesso_cliente = new TelaClientes(operacao);
        acesso_cliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteExcluirTitleActionPerformed

    private void clienteConsultarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteConsultarTitleActionPerformed
        TelaConsultarTabela telaConsulta = new TelaConsultarTabela("CLIENTES");
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_clienteConsultarTitleActionPerformed

    private void agenEditarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenEditarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        TelaAgencias acesso_cliente = new TelaAgencias(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_agenEditarTitleActionPerformed

    private void agenExcluirTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenExcluirTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        TelaAgencias acesso_cliente = new TelaAgencias(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_agenExcluirTitleActionPerformed

    private void agenConsultarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenConsultarTitleActionPerformed
        // TODO add your handling code here:
        TelaConsultarTabela telaConsulta = new TelaConsultarTabela("AGENCIAS");
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_agenConsultarTitleActionPerformed

    private void contaEditarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaEditarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        TelaContas acesso_cliente = new TelaContas(operacao);
        acesso_cliente.setVisible(true);
        
    }//GEN-LAST:event_contaEditarTitleActionPerformed

    private void contaExcluirTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaExcluirTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        TelaContas acesso_cliente = new TelaContas(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_contaExcluirTitleActionPerformed

    private void contaConsultarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaConsultarTitleActionPerformed
        // TODO add your handling code here:
        TelaConsultarTabela telaConsulta = new TelaConsultarTabela("CONTACORRENTE");
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_contaConsultarTitleActionPerformed

    private void extratoEditarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratoEditarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        TelaExtratos acesso_cliente = new TelaExtratos(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_extratoEditarTitleActionPerformed

    private void extratoExcluirTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratoExcluirTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        TelaExtratos acesso_cliente = new TelaExtratos(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_extratoExcluirTitleActionPerformed

    private void extratoConsultarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratoConsultarTitleActionPerformed
        // TODO add your handling code here:
        TelaConsultarTabela telaConsulta = new TelaConsultarTabela("MOVIMENTACAO");
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_extratoConsultarTitleActionPerformed

    private void histEditarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histEditarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        TelaHistoricos acesso_cliente = new TelaHistoricos(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_histEditarTitleActionPerformed

    private void histExcluirTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histExcluirTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        TelaHistoricos acesso_cliente = new TelaHistoricos(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_histExcluirTitleActionPerformed

    private void histConsultarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histConsultarTitleActionPerformed
        // TODO add your handling code here:
        TelaConsultarTabela telaConsulta = new TelaConsultarTabela("HISTORICOS");
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_histConsultarTitleActionPerformed

    private void usuarioEditarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEditarTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        TelaUsuarios acesso_cliente = new TelaUsuarios(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_usuarioEditarTitleActionPerformed

    private void usuarioExcluirTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioExcluirTitleActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        TelaUsuarios acesso_cliente = new TelaUsuarios(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_usuarioExcluirTitleActionPerformed

    private void usuarioConsultarTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioConsultarTitleActionPerformed
        // TODO add your handling code here:
        TelaConsultarTabela telaConsulta = new TelaConsultarTabela("USUARIOS");
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_usuarioConsultarTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agenConsultarTitle;
    private javax.swing.JMenuItem agenCriarTitle;
    private javax.swing.JMenuItem agenEditarTitle;
    private javax.swing.JMenuItem agenExcluirTitle;
    private javax.swing.JMenu agenMenuTitle;
    private javax.swing.JMenuItem clienteConsultarTitle;
    private javax.swing.JMenuItem clienteCriarTitle;
    private javax.swing.JMenuItem clienteEditarTitle;
    private javax.swing.JMenuItem clienteExcluirTitle;
    private javax.swing.JMenu clienteMenuTitle;
    private javax.swing.JMenuItem contaConsultarTitle;
    private javax.swing.JMenuItem contaCriarTitle;
    private javax.swing.JMenuItem contaEditarTitle;
    private javax.swing.JMenuItem contaExcluirTitle;
    private javax.swing.JMenu contaMenuTitle;
    private javax.swing.JMenuItem extratoConsultarTitle;
    private javax.swing.JMenuItem extratoCriarTitle;
    private javax.swing.JMenuItem extratoEditarTitle;
    private javax.swing.JMenuItem extratoExcluirTitle;
    private javax.swing.JMenu extratoMenuTitle;
    private javax.swing.JMenuItem histConsultarTitle;
    private javax.swing.JMenuItem histCriarTitle;
    private javax.swing.JMenuItem histEditarTitle;
    private javax.swing.JMenuItem histExcluirTitle;
    private javax.swing.JMenu histMenuTitle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem usuarioConsultarTitle;
    private javax.swing.JMenuItem usuarioCriarTitle;
    private javax.swing.JMenuItem usuarioEditarTitle;
    private javax.swing.JMenuItem usuarioExcluirTitle;
    private javax.swing.JMenu usuarioMenuTitle;
    // End of variables declaration//GEN-END:variables
}
