/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ContaCorrente;
import DAO.connectDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaContas extends javax.swing.JFrame {

    /**
     * Creates new form Contas
     */
    public TelaContas() {
        initComponents();
    }
    
    String operacaoAtivaGlobal = "Nenhum";
    public TelaContas(String operacaoAtiva){
        initComponents();
        
        operacaoAtivaGlobal = operacaoAtiva;
        
        String operacao = "Incluir";
        
        if(operacaoAtiva.equals(operacao)){
            idTitle.setVisible(true);
            ContaConta.setVisible(true);
            AgenciaConta.setVisible(true);
            SaldoConta.setVisible(true);
            IDConta.setVisible(true);        
            
            ButtonCadastrar.setVisible(true);
            ButtonDetalhes.setVisible(true);            
        }
        
        operacao = "Alterar";
        
        if(operacaoAtiva.equals(operacao)){
            idTitle.setVisible(true);
            ContaConta.setVisible(false);
            AgenciaConta.setVisible(false);
            SaldoConta.setVisible(false);
            IDConta.setVisible(true);  
            
            ButtonCadastrar.setVisible(true);
            ButtonDetalhes.setVisible(false);   
            
            ButtonCadastrar.setText("Pesquisar");
        }       
        
        operacao = "Excluir";
        
        if(operacaoAtiva.equals(operacao)){
            idTitle.setVisible(true);
            ContaConta.setVisible(false);
            AgenciaConta.setVisible(false);
            SaldoConta.setVisible(false);
            IDConta.setVisible(true);    
            
            ButtonCadastrar.setVisible(false);
            ButtonDetalhes.setVisible(false);   
            
            ButtonCadastrar.setText("Excluir");
        }
    }   
 
    ContaCorrente conta_tela = new ContaCorrente();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contaTitle = new javax.swing.JLabel();
        ContaConta = new javax.swing.JTextField();
        agenciaTitle = new javax.swing.JLabel();
        AgenciaConta = new javax.swing.JTextField();
        idTitle = new javax.swing.JLabel();
        IDConta = new javax.swing.JTextField();
        saldoTitle = new javax.swing.JLabel();
        SaldoConta = new javax.swing.JTextField();
        ButtonCadastrar = new javax.swing.JButton();
        ButtonDetalhes = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contaTitle.setText("Conta");

        ContaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaContaActionPerformed(evt);
            }
        });

        agenciaTitle.setText("Agência");

        AgenciaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaContaActionPerformed(evt);
            }
        });

        idTitle.setText("ID");

        IDConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDContaActionPerformed(evt);
            }
        });

        saldoTitle.setText("Saldo");

        SaldoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoContaActionPerformed(evt);
            }
        });

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        ButtonDetalhes.setText("Detalhes");
        ButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDetalhesActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDetalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Limpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contaTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agenciaTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgenciaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDConta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldoTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaldoConta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contaTitle)
                    .addComponent(idTitle)
                    .addComponent(IDConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agenciaTitle)
                    .addComponent(AgenciaConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoTitle)
                    .addComponent(SaldoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrar)
                    .addComponent(ButtonDetalhes)
                    .addComponent(Limpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContaContaActionPerformed

    private void AgenciaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgenciaContaActionPerformed

    private void IDContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDContaActionPerformed

    private void SaldoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoContaActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        System.out.println(operacaoAtivaGlobal);
        String operacaoExcluir
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){        
            try{
            conta_tela.setNum_agencia(AgenciaConta.getText());
            conta_tela.setNum_conta(ContaConta.getText());
            conta_tela.setID_cliente(IDConta.getText());
            conta_tela.setSaldo(Float.valueOf(SaldoConta.getText()));

            connectDAO DaoConta = new connectDAO();
                DaoConta.connectDB();
                DaoConta.insereRegistroJFBD("CONTACORRENTE", conta_tela.dadosSQLValues());
            }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this, "Conta Cadastrada");
            this.setVisible(false);
            this.dispose();            
        }
        
        operacao = "Alteração";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            try{
            conta_tela.setNum_agencia(AgenciaConta.getText());
            conta_tela.setNum_conta(ContaConta.getText());
            conta_tela.setID_cliente(IDConta.getText());
            conta_tela.setSaldo(Float.valueOf(SaldoConta.getText()));

            connectDAO DaoConta = new connectDAO();
                DaoConta.connectDB();
                DaoConta.alteraRegistroJFBD("CONTACORRENTE", conta_tela.alterarDadosSQLValues(), "ID_CLI='"+conta_tela.getIDConta()+"'");
            }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
             
            }
            
            JOptionPane.showMessageDialog(this, "Conta Alterada");
            this.setVisible(false);
            this.dispose();            
        }
        
        operacao = "Alterar";
        operacaoExcluir = "Excluir";
        if (operacaoAtivaGlobal.equals(operacao) || operacaoAtivaGlobal.equals(operacaoExcluir)){
            System.out.println("pesquisar para alterar");
            connectDAO DaoConta = new connectDAO();
            
            conta_tela = DaoConta.pesquisaContaJFBD(
                    this.conta_tela.getTabela(),
                    this.conta_tela.pesquisaSQLValues(),
                    "ID_CLI='"+this.IDConta.getText()+"'"
            );
            
            System.out.println("retornou, não deu erro silencioso");
            
            this.AgenciaConta.setText(conta_tela.getNum_agencia());
            this.ContaConta.setText(conta_tela.getNum_conta());
            this.IDConta.setText(conta_tela.getID_cliente());
            this.SaldoConta.setText(conta_tela.getSaldo().toString());
            
        }
        
        
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void ButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDetalhesActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        AgenciaConta.setText(" ");
        ContaConta.setText(" ");
        SaldoConta.setText(" ");
        IDConta.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgenciaConta;
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonDetalhes;
    private javax.swing.JTextField ContaConta;
    private javax.swing.JTextField IDConta;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField SaldoConta;
    private javax.swing.JLabel agenciaTitle;
    private javax.swing.JLabel contaTitle;
    private javax.swing.JLabel idTitle;
    private javax.swing.JLabel saldoTitle;
    // End of variables declaration//GEN-END:variables
}
