/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Agencia;
import DAO.connectDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaAgencias extends javax.swing.JFrame {

    /**
     * Creates new form Agencia
     */
    public TelaAgencias() {
        initComponents();
    }

    String operacaoAtivaGlobal = "Nenhum";
    public TelaAgencias(String operacaoAtiva){
        initComponents ();
        
        operacaoAtivaGlobal = operacaoAtiva;
        
        String operacao = "Incluir";
        
        if(operacaoAtiva.equals(operacao)){
            agenciaTitle.setVisible(true);
            AgenciaAgencia.setVisible(true);
            NomeAgencia.setVisible(true);
            EndAgencia.setVisible(true);
            NumAgencia.setVisible(true);
            CompAgencia.setVisible(true);
            BairroAgencia.setVisible(true);
            CEPAgencia.setVisible(true);
            CidadeAgencia.setVisible(true);
            UFAgencia.setVisible(true);
            TelefoneAgencia.setVisible(true);
            
            ButtonCadastrar.setVisible(true);
            ButtonDetalhes.setVisible(true);                    
        }
        
        operacao = "Alterar";
        
        if(operacaoAtiva.equals(operacao)){
            agenciaTitle.setVisible(true);
            AgenciaAgencia.setVisible(true);
            NomeAgencia.setVisible(false);
            EndAgencia.setVisible(false);
            NumAgencia.setVisible(false);
            CompAgencia.setVisible(false);
            BairroAgencia.setVisible(false);
            CEPAgencia.setVisible(false);
            CidadeAgencia.setVisible(false);
            UFAgencia.setVisible(false);
            TelefoneAgencia.setVisible(false);
            
            ButtonCadastrar.setVisible(true);
            ButtonDetalhes.setVisible(false);   
            
            ButtonCadastrar.setText("Pesquisar");
        }       
        
        operacao = "Excluir";
        
        if(operacaoAtiva.equals(operacao)){
            agenciaTitle.setVisible(true);
            AgenciaAgencia.setVisible(true);
            NomeAgencia.setVisible(false);
            EndAgencia.setVisible(false);
            NumAgencia.setVisible(false);
            CompAgencia.setVisible(false);
            BairroAgencia.setVisible(false);
            CEPAgencia.setVisible(false);
            CidadeAgencia.setVisible(false);
            UFAgencia.setVisible(false);
            TelefoneAgencia.setVisible(false);  
            
            ButtonCadastrar.setVisible(false);
            ButtonDetalhes.setVisible(false);   
            
            ButtonCadastrar.setText("Excluir");
        }
        
    }
    
    
    Agencia agencia_tela = new Agencia();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTitle = new javax.swing.JLabel();
        NomeAgencia = new javax.swing.JTextField();
        endTitle = new javax.swing.JLabel();
        EndAgencia = new javax.swing.JTextField();
        numTitle = new javax.swing.JLabel();
        NumAgencia = new javax.swing.JTextField();
        compTitle = new javax.swing.JLabel();
        CompAgencia = new javax.swing.JTextField();
        bairroTitle = new javax.swing.JLabel();
        BairroAgencia = new javax.swing.JTextField();
        cepTitle = new javax.swing.JLabel();
        CEPAgencia = new javax.swing.JTextField();
        cidadeTitle = new javax.swing.JLabel();
        CidadeAgencia = new javax.swing.JTextField();
        ufTitle = new javax.swing.JLabel();
        UFAgencia = new javax.swing.JComboBox<>();
        agenciaTitle = new javax.swing.JLabel();
        AgenciaAgencia = new javax.swing.JTextField();
        telTitle = new javax.swing.JLabel();
        TelefoneAgencia = new javax.swing.JTextField();
        ButtonCadastrar = new javax.swing.JButton();
        ButtonDetalhes = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeTitle.setText("Nome");

        NomeAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAgenciaActionPerformed(evt);
            }
        });

        endTitle.setText("Endereço:");

        EndAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndAgenciaActionPerformed(evt);
            }
        });

        numTitle.setText("Número:");

        NumAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumAgenciaActionPerformed(evt);
            }
        });

        compTitle.setText("Complemento:");

        CompAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompAgenciaActionPerformed(evt);
            }
        });

        bairroTitle.setText("Bairro:");

        BairroAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroAgenciaActionPerformed(evt);
            }
        });

        cepTitle.setText("CEP");

        CEPAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPAgenciaActionPerformed(evt);
            }
        });

        cidadeTitle.setText("Cidade");

        CidadeAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeAgenciaActionPerformed(evt);
            }
        });

        ufTitle.setText("UF");

        UFAgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MS", "MT", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        UFAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFAgenciaActionPerformed(evt);
            }
        });

        agenciaTitle.setText("Agência");

        AgenciaAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaAgenciaActionPerformed(evt);
            }
        });

        telTitle.setText("Telefone");

        TelefoneAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneAgenciaActionPerformed(evt);
            }
        });

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        ButtonDetalhes.setText("Detalhes");
        ButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDetalhesActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bairroTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BairroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cepTitle)
                        .addGap(13, 13, 13)
                        .addComponent(CEPAgencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDetalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Limpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ufTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidadeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CidadeAgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelefoneAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CompAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(endTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EndAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agenciaTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgenciaAgencia)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTitle)
                    .addComponent(agenciaTitle)
                    .addComponent(AgenciaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTitle)
                    .addComponent(EndAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTitle)
                    .addComponent(NumAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compTitle)
                    .addComponent(CompAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroTitle)
                    .addComponent(BairroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepTitle)
                    .addComponent(CEPAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufTitle)
                    .addComponent(UFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTitle)
                    .addComponent(CidadeAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telTitle)
                    .addComponent(TelefoneAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrar)
                    .addComponent(ButtonDetalhes)
                    .addComponent(Limpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAgenciaActionPerformed

    private void EndAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndAgenciaActionPerformed

    private void NumAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumAgenciaActionPerformed

    private void CompAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompAgenciaActionPerformed

    private void BairroAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroAgenciaActionPerformed

    private void CEPAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPAgenciaActionPerformed

    private void CidadeAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeAgenciaActionPerformed

    private void UFAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFAgenciaActionPerformed

    private void AgenciaAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgenciaAgenciaActionPerformed

    private void TelefoneAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneAgenciaActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        System.out.println(operacaoAtivaGlobal);
        String operacaoExcluir;
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            try {
            agencia_tela.setNum_Agencia(AgenciaAgencia.getText());
            agencia_tela.setNome(NomeAgencia.getText());
            agencia_tela.setEndereco(EndAgencia.getText());
            agencia_tela.setNumero(NumAgencia.getText());
            agencia_tela.setComplemento(CompAgencia.getText());
            agencia_tela.setBairro(BairroAgencia.getText());
            agencia_tela.setCEP(CEPAgencia.getText());
            agencia_tela.setCidade(CidadeAgencia.getText());
            agencia_tela.setUF(UFAgencia.getSelectedItem().toString());
            agencia_tela.setTelefone(TelefoneAgencia.getText());
            
            connectDAO DaoAgencia = new connectDAO();
            DaoAgencia.connectDB();
            DaoAgencia.insereRegistroJFBD("AGENCIAS", agencia_tela.dadosSQLValues());
        } catch(Exception erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Agencia Cadastrada");
        this.setVisible(false);
        this.dispose();
        }
        
        operacao = "Alteração";
        if(operacaoAtivaGlobal.equals(operacao)){
            try {
            agencia_tela.setNum_Agencia(AgenciaAgencia.getText());
            agencia_tela.setNome(NomeAgencia.getText());
            agencia_tela.setEndereco(EndAgencia.getText());
            agencia_tela.setNumero(NumAgencia.getText());
            agencia_tela.setComplemento(CompAgencia.getText());
            agencia_tela.setBairro(BairroAgencia.getText());
            agencia_tela.setCEP(CEPAgencia.getText());
            agencia_tela.setCidade(CidadeAgencia.getText());
            agencia_tela.setUF(UFAgencia.getSelectedItem().toString());
            agencia_tela.setTelefone(TelefoneAgencia.getText());
            
            connectDAO DaoAgencia = new connectDAO();
            DaoAgencia.connectDB();
            DaoAgencia.insereRegistroJFBD("AGENCIAS", agencia_tela.dadosSQLValues());
        } catch(Exception erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Agencia Aletrada");
        this.setVisible(false);
        this.dispose();
        }
        
        operacao = "Alterar";
        operacaoExcluir = "Excluir";
        if(operacaoAtivaGlobal.equals(operacao) || operacaoAtivaGlobal.equals(operacaoExcluir)){
           System.out.println("pesquisar para alterar");
           connectDAO DaoConta = new connectDAO();
           
           List<String> dadosSQL = DaoConta.pesquisaRegistroJFBD(
                   this.agencia_tela.getTabela(),
                   this.agencia_tela.pesquisaSQLValues(),
                   "NUM_AGE='"+this.NumAgencia.getText()+"'"
           );
           
           agencia_tela.importaSQLValues(dadosSQL);
           
           System.out.println("retornou, não deu erro silencioso");
           
           this.AgenciaAgencia.setText(agencia_tela.getNum_Agencia());
           this.NomeAgencia.setText(agencia_tela.getNome());
           this.EndAgencia.setText(agencia_tela.getEndereco());
           this.NumAgencia.setText(agencia_tela.getNumero());
           this.CompAgencia.setText(agencia_tela.getComplemento());
           this.BairroAgencia.setText(agencia_tela.getBairro());
           this.CEPAgencia.setText(agencia_tela.getCEP());
           this.CidadeAgencia.setText(agencia_tela.getCidade());
           this.UFAgencia.setSelectedItem(agencia_tela.getUF());
           this.TelefoneAgencia.setText(agencia_tela.getTelefone());
           
           AgenciaAgencia.setVisible(false);
           NomeAgencia.setVisible(false);
           EndAgencia.setVisible(true);
           NumAgencia.setVisible(true);
           CompAgencia.setVisible(true);
           BairroAgencia.setVisible(true);
           CEPAgencia.setVisible(true);
           CidadeAgencia.setVisible(true);
           UFAgencia.setVisible(true);
           TelefoneAgencia.setVisible(true);
           
           if(operacaoAtivaGlobal.equals(operacaoExcluir)){
               ButtonCadastrar.setText("Excluir");
               operacaoAtivaGlobal = "Exclusão";
           } else {
               ButtonCadastrar.setText("Alterar");
               operacaoAtivaGlobal = "Alteração";
           }
           
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void ButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDetalhesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ButtonDetalhesActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        AgenciaAgencia.setText(" ");
        NomeAgencia.setText(" ");
        EndAgencia.setText(" ");
        NumAgencia.setText(" ");
        CompAgencia.setText(" ");
        BairroAgencia.setText(" ");
        CEPAgencia.setText(" ");
        CidadeAgencia.setText(" ");
        UFAgencia.setSelectedIndex(0);
        TelefoneAgencia.setText(" ");

        // TODO add your handling code here:
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgenciaAgencia;
    private javax.swing.JTextField BairroAgencia;
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonDetalhes;
    private javax.swing.JTextField CEPAgencia;
    private javax.swing.JTextField CidadeAgencia;
    private javax.swing.JTextField CompAgencia;
    private javax.swing.JTextField EndAgencia;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField NomeAgencia;
    private javax.swing.JTextField NumAgencia;
    private javax.swing.JTextField TelefoneAgencia;
    private javax.swing.JComboBox<String> UFAgencia;
    private javax.swing.JLabel agenciaTitle;
    private javax.swing.JLabel bairroTitle;
    private javax.swing.JLabel cepTitle;
    private javax.swing.JLabel cidadeTitle;
    private javax.swing.JLabel compTitle;
    private javax.swing.JLabel endTitle;
    private javax.swing.JLabel nomeTitle;
    private javax.swing.JLabel numTitle;
    private javax.swing.JLabel telTitle;
    private javax.swing.JLabel ufTitle;
    // End of variables declaration//GEN-END:variables
}
