/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ContaCorrente;
import DAO.Usuario;
import DAO.connectDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public TelaUsuarios() {
        initComponents();
    }
    
    String operacaoAtivaGlobal = "Nenhum";
    public TelaUsuarios(String operacaoAtiva){
        initComponents();
        
        operacaoAtivaGlobal = operacaoAtiva;
        
        String operacao = "Incluir";
        
        if(operacaoAtiva.equals(operacao)){
            idTitle.setVisible(true);
            IDUsuario.setVisible(true);
            Num_agenciaUsuario.setVisible(true);
            SenhaUsuario.setVisible(true);
            Num_contaUsuario.setVisible(true);
            
            ButtonCadastrar.setVisible(true);
            ButtonDetalhes.setVisible(true); 
        }
        
        operacao = "Alterar";
        
        if(operacaoAtiva.equals(operacao)){
            idTitle.setVisible(true);
            IDUsuario.setVisible(true);
            Num_agenciaUsuario.setVisible(false);
            SenhaUsuario.setVisible(false);
            Num_contaUsuario.setVisible(false);
            
            ButtonCadastrar.setVisible(true);
            ButtonDetalhes.setVisible(false); 
            
            ButtonCadastrar.setText("Pesquisar");
        }
        
        operacao = "Excluir";
        
        if(operacaoAtiva.equals(operacao)){
            idTitle.setVisible(true);
            IDUsuario.setVisible(true);
            Num_agenciaUsuario.setVisible(false);
            SenhaUsuario.setVisible(false);
            Num_contaUsuario.setVisible(false);
            
            ButtonCadastrar.setVisible(false);
            ButtonDetalhes.setVisible(false); 
            
            ButtonCadastrar.setText("Excluir");
            
        }
    }
    
    Usuario usuario_tela = new Usuario();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTitle = new javax.swing.JLabel();
        IDUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Num_agenciaUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SenhaUsuario = new javax.swing.JTextField();
        ButtonCadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Num_contaUsuario = new javax.swing.JTextField();
        ButtonDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idTitle.setText("ID:");

        IDUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Agencia:");

        Num_agenciaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_agenciaUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha:");

        SenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaUsuarioActionPerformed(evt);
            }
        });

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Conta");

        Num_contaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num_contaUsuarioActionPerformed(evt);
            }
        });

        ButtonDetalhes.setText("Detalhes");
        ButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(273, 273, 273))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonDetalhes)
                                .addGap(41, 41, 41)
                                .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num_contaUsuario)
                                    .addComponent(Num_agenciaUsuario))
                                .addGap(12, 12, 12)
                                .addComponent(idTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Num_agenciaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Num_contaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrar)
                    .addComponent(ButtonDetalhes)
                    .addComponent(Limpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDUsuarioActionPerformed

    private void Num_agenciaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_agenciaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num_agenciaUsuarioActionPerformed

    private void SenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaUsuarioActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        System.out.println(operacaoAtivaGlobal);
        String operacaoExcluir;
        String operacao = "Incluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            try {
                usuario_tela.setID_cliente(IDUsuario.getText());
                usuario_tela.setNum_agencia(Num_agenciaUsuario.getText());
                usuario_tela.setNum_conta(Num_contaUsuario.getText());
                usuario_tela.setSenha(SenhaUsuario.getText());

                connectDAO DaoUsuario = new connectDAO();
                DaoUsuario.connectDB();
                DaoUsuario.insereRegistroJFBD("USUARIOS", usuario_tela.dadosSQLValues());
            }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this, "Usuario Cadastrado");
            this.setVisible(false);
            this.dispose();
        }
        
        operacao = "Alteração";
        if(operacaoAtivaGlobal.equals(operacao)){
            try {
                usuario_tela.setID_cliente(IDUsuario.getText());
                usuario_tela.setNum_agencia(Num_agenciaUsuario.getText());
                usuario_tela.setNum_conta(Num_contaUsuario.getText());
                usuario_tela.setSenha(SenhaUsuario.getText());

                connectDAO DaoUsuario = new connectDAO();
                DaoUsuario.connectDB();
                DaoUsuario.alteraRegistroJFBD("USUARIOS", usuario_tela.alterarDadosSQLValues(), "ID='"+usuario_tela.getID_cliente()+"'");
            }catch(Exception erro){
                JOptionPane.showMessageDialog(this, erro.getMessage());
                
            }

            JOptionPane.showMessageDialog(this, "Usuario Cadastrado");
            this.setVisible(false);
            this.dispose();
        }

        operacao = "Alterar";
        operacaoExcluir = "Excluir";
        if (operacaoAtivaGlobal.equals(operacao) || operacaoAtivaGlobal.equals(operacaoExcluir)){
            System.out.println("pesquisar para alterar");
            connectDAO DaoConta = new connectDAO();
            
            List<String> dadosSQL = DaoConta.pesquisaRegistroJFBD(
                    this.usuario_tela.getTabela(),
                    this.usuario_tela.pesquisaSQLValues(),
                    "ID='"+this.IDUsuario.getText()+"'"
            );
            
            usuario_tela.importaSQLValues(dadosSQL);
            
            System.out.println("retornou, não deu erro silencioso");
            
            this.IDUsuario.setText(usuario_tela.getID_cliente());
            this.Num_agenciaUsuario.setText(usuario_tela.getNum_agencia());
            this.Num_contaUsuario.setText(usuario_tela.getNum_conta());
            this.SenhaUsuario.setText(usuario_tela.getSenha());
            
            idTitle.setVisible(false);
            IDUsuario.setVisible(false);
            Num_agenciaUsuario.setVisible(true);
            SenhaUsuario.setVisible(false);
            Num_contaUsuario.setVisible(false);
            
            if(operacaoAtivaGlobal.equals(operacaoExcluir)) {
                ButtonCadastrar.setText("Excluir");
                operacaoAtivaGlobal = "Exclusão";
            } else {
                ButtonCadastrar.setText("Alterar");
                operacaoAtivaGlobal = "Alteração";
            }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        IDUsuario.setText(" ");
        Num_agenciaUsuario.setText(" ");
        Num_contaUsuario.setText(" ");
        SenhaUsuario.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_LimparActionPerformed

    private void Num_contaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num_contaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num_contaUsuarioActionPerformed

    private void ButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonDetalhes;
    private javax.swing.JTextField IDUsuario;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField Num_agenciaUsuario;
    private javax.swing.JTextField Num_contaUsuario;
    private javax.swing.JTextField SenhaUsuario;
    private javax.swing.JLabel idTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
